# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-08 15:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myprofile', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='thing',
            options={'verbose_name_plural': 'EasyReturn Profile'},
        ),
    ]
