# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-10 18:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprofile', '0002_auto_20160608_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='thing',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
