# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-10 18:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprofile', '0004_auto_20160610_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thing',
            name='slug',
            field=models.SlugField(),
        ),
    ]
